#!/bin/bash

if [ $# -ne 2 ]; then
  echo "illegal arguments count"
  exit 1
elif [ ! -f $1 ]; then
  echo "file not exist"
  exit 1
else

echo "Top 5 IP:"
grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' $1 | sort | uniq -c | sort -nr | head -n $2

echo "Top 5 links:"
grep -oE '((GET|POST|PROPFIND|HEAD) (/?(\w)*[+-]*\.?(\w)*)*)' $1 | grep -oE ' (/?(\w)*[+-]*\.?(\w)*)*' | sort  | uniq -c | sort -nr | head -n $2

fi
exit 0
